# Generated by Django 5.0.2 on 2024-09-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_parent_task_task_progress_task_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence',
        ),
    ]
