# Generated by Django 5.0.2 on 2024-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_task_parent_task_remove_task_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=7),
        ),
        migrations.AddField(
            model_name='task',
            name='reference_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
