# Generated by Django 5.0.2 on 2024-09-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_attachment_task_recurrence_task_reference_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reference_link',
        ),
    ]
