# Generated by Django 5.0.2 on 2024-09-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_task_attachment_remove_task_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
