# Generated by Django 5.0.2 on 2024-09-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
