# Generated by Django 5.0.2 on 2024-09-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_event_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
